2020-07-05 | 20:07:49 | Data is ready to be passed to a ML model.
2020-07-05 | 20:11:02 | Data is ready to be passed to a ML model.
2020-07-05 | 20:18:34 | Data is ready to be passed to a ML model.
2020-07-05 | 20:21:47 | Data is ready to be passed to a ML model.
2020-07-05 | 20:56:18 | Something went wrong while getting data ready for a ML model: saveModel() missing 1 required positional argument: 'fileName'
2020-07-05 | 20:56:18 | Something went wrong while training the model: saveModel() missing 1 required positional argument: 'fileName'
2020-07-05 | 20:58:54 | Something went wrong while getting data ready for a ML model: saveModel() missing 1 required positional argument: 'fileName'
2020-07-05 | 20:58:54 | Something went wrong while training the model: saveModel() missing 1 required positional argument: 'fileName'
2020-07-05 | 21:02:50 | Something went wrong while getting data ready for a ML model: 'Operation' object has no attribute 'modelDirPath'
2020-07-05 | 21:02:50 | Something went wrong while training the model: 'Operation' object has no attribute 'modelDirPath'
2020-07-05 | 21:05:02 | Data is ready to be passed to a ML model.
2020-07-05 | 21:25:08 | Data is ready to be passed to a ML model.
2020-07-05 | 21:26:15 | Something went wrong while training the model: local variable 'name' referenced before assignment
2020-07-05 | 21:28:10 | Data is ready to be passed to a ML model.
2020-07-05 | 21:29:20 | Something went wrong while training the model: 'popitem(): dictionary is empty'
2020-07-05 | 21:37:02 | Data is ready to be passed to a ML model.
2020-07-05 | 21:38:07 | Something went wrong while training the model: 'popitem(): dictionary is empty'
2020-07-05 | 21:40:54 | Data is ready to be passed to a ML model.
2020-07-05 | 21:43:39 | Something went wrong while training the model: 'popitem(): dictionary is empty'
2020-07-05 | 21:56:38 | Data is ready to be passed to a ML model.
2020-07-05 | 22:40:03 | Something went wrong while training the model: 'AxesSubplot' object has no attribute 'xlabel'
2020-07-05 | 22:43:51 | Data is ready to be passed to a ML model.
2020-07-05 | 22:55:03 | Something went wrong while training the model: [Errno 2] No such file or directory: 'Models/ExtraTrees_1/evalution_plot.png'
2020-07-05 | 22:56:47 | Data is ready to be passed to a ML model.
2020-07-05 | 23:22:47 | Something went wrong while training the model: Invalid parameter extratreesregressor for estimator Pipeline(steps=[('standardscaler', StandardScaler()),
                ('xgbregressor',
                 XGBRegressor(base_score=None, booster=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, gamma=None, gpu_id=None,
                              importance_type='gain',
                              interaction_constraints=None, learning_rate=None,
                              max_delta_step=None, max_depth=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, n_estimators=100,
                              n_jobs=None, num_parallel_tree=None,
                              random_state=42, reg_alpha=None, reg_lambda=None,
                              scale_pos_weight=None, subsample=None,
                              tree_method=None, validate_parameters=None,
                              verbosity=None))]). Check the list of available parameters with `estimator.get_params().keys()`.
2020-07-06 | 21:53:17 | Data is ready to be passed to a ML model.
2020-07-06 | 21:54:24 | Something went wrong while training the model: 'FindBestModels' object has no attribute 'xgboost'
2020-07-06 | 21:57:17 | Data is ready to be passed to a ML model.
2020-07-06 | 21:58:26 | Something went wrong while training the model: 'FindBestModels' object has no attribute 'extratrees'
2020-07-06 | 22:02:02 | Data is ready to be passed to a ML model.
2020-07-07 | 08:37:50 | Data is ready to be passed to a ML model.
2020-07-07 | 10:28:17 | Model training has been completed successfully.
2020-07-31 | 18:00:20 | Something went wrong while getting data ready for a ML model: [Errno 2] File DataFrom_Db/training_set.csv does not exist: 'DataFrom_Db/training_set.csv'
2020-07-31 | 18:00:20 | Something went wrong while training the model: [Errno 2] File DataFrom_Db/training_set.csv does not exist: 'DataFrom_Db/training_set.csv'
2020-07-31 | 18:12:24 | Data is ready to be passed to a ML model.
2020-07-31 | 22:50:00 | Data is ready to be passed to a ML model.
